config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'groups#index'

    resources :users do
      collection do
        get 'search'
      end
    end

    # resources :users, only: [:edit, :update]
    resources :groups do
      resources :messages
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages

  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to  :group
  belongs_to  :user

  validates   :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :members
          has_many :groups, through: :members
          has_many :messages
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  before_action :basic_auth, if: :production?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def edit
    @group = Group.find(params[:id])

  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end

  end

    def update

    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'

    else
      render :edit
    end

  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @newmessages = []
    respond_to do |format|
      format.json {
        if params[:leastMessage][:id].to_i != @group.messages.last.id
          @newmessages = @group.messages.where("id > #{params[:leastMessage][:id]}")
        end
      }
      format.html
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def search
    @users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%" ,current_user)

    respond_to do |format|
       format.html
       format.json
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_space/_side_contents.html.haml
.contents__left-contents__groupform
  - current_user.groups.each do |group|
    .contents__left-contents__groupform__group
      = group.name
    .contents__left-contents__groupform__group__text さようなら



/ .contents__left-contents__groupform
/   .contents__left-contents__groupform__group test-group
/   .contents__left-contents__groupform__group__text さようなら

app/views/groups/_form.html.erb
<%= form_for [@group]  do |f| %>
  <div class="edit_chat_group">

    <div class='chat-group-form__field clearfix'>
        <!-- グループ名表示、入力定義 -->
        <div class='chat-group-form__field--left'>
            <%= f.label :グループ名, class: "chat-group-form__label" %>
        </div>
        <div class='chat-group-form__field--right'>
            <%= f.text_field :name, class:"chat-group-form__input" %>
        </div>
    </div>

    <div class='chat-group-form__field clearfix'>
      <div class='chat-group-form__field--left'>
        <div class="chat-group-form__label" >
          <%= f.label :チャットメンバーを追加 %>
        </div>
      </div>
      <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
          <%= f.text_field :name , class:'chat-group-form__input', id: 'user-search-field', placeholder: '追加したいユーザを選択してください' %>
        </div>
        <div id='user-search-result'>
            <!-- ここに追加される -->
        </div>
      </div>
    </div>

    <div class='chat-group-form__field clearfix'>
      <div class = "chat-group-form__field.clearfix" >
        <div class = "chat-group-form__field--left" >
          <label class = "chat-group-form__label" for = "chat_group_チャットメンバー"> チャットメンバー </label>
        </div>
        <div class = "chat-group-form__field--right">
          <% @group.users.each do | user | %>
            <div id='chat-group-users'>
              <div class='chat-group-user clearfix' id='chat-group-user-22'>
                <p class='chat-group-user__name'><%= user.name %></p>
                <input name='group[user_ids][]' type='hidden' value='<%= user.id %>'>
              </div>
            </div>
          <% end %>
          <div id='user-member-list'>
              <!-- ここに追加される -->
          </div>
        </div>
      </div>
    </div>


      <div class='chat-group-form__field clearfix'>
          <div class = "chat-group-form__field--right" >
            <%= f.submit '更新する', class: "chat-group-form__action-btn" %>
          </div>
      </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='chat-group-form'>
  <h1>チャットグループ編集</h1>
  <%= form_for [@group]  do |f| %>
    <div class="edit_chat_group">

       <div class='chat-group-form__field clearfix'>

        <!-- グループ名表示、入力定義 -->
        <div class='chat-group-form__field--left'>
            <%= f.label :グループ名, class: "chat-group-form__label" %>
        </div>
        <div class='chat-group-form__field--right'>
            <%= f.text_field :name, class:"chat-group-form__input" %>
        </div>

      </div>

      <div class='chat-group-form__field clearfix'>

        <!-- メンバー追加、入力定義 -->
        <div class='chat-group-form__field--left'>
          <div class="chat-group-form__label" >
            <%= f.label :チャットメンバーを追加 %>
          </div>
        </div>

        <div class='chat-group-form__field--right'>
          <div class='chat-group-form__search clearfix'>
            <%= f.text_field :name , class:'chat-group-form__input', id: 'user-search-field', placeholder: '追加したいユーザを選択してください' %>
          </div>
          <div id='user-search-result'>
              <!-- ここに追加される -->
          </div>
        </div>

      <div class='chat-group-form__field clearfix'>


      <%= f.submit '更新する', class: "chat-group-form__action-btn" %>
      </div>

    </div>

  <% end %>
</div>

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.contents
  = render 'shared/side_contents'

app/views/groups/new.html.erb
<div class='chat-group-form'>
  <h1>新規チャットグループ</h1>
  <form class="new_chat_group" id="new_chat_group" action="/chat_groups" accept-charset="UTF-8" method="post">
    <div class="chat-group-form__errors">
      <h2>1件のエラーが発生しました。
      <ul>
        <li>エラーです</li>
      </ul>
    </div>
    <div class='chat-group-form__field clearfix'>
      <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_name">グループ名</label>
      </div>
      <div class='chat-group-form__field--right'>
        <input class="chat-group-form__input" placeholder="グループ名を入力してください" type="text" name="chat_group[name]" id="chat_group_name" />
      </div>
    </div>
    <div class='chat-group-form__field clearfix'>
      <!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します  -->
      <!-- <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
      </div>
      <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
          <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
      </div>-->
    </div>
    <div class='chat-group-form__field clearfix'>
      <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバー">チャットメンバー</label>
      </div>
      <div class='chat-group-form__field--right'>
        <!-- グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください  -->
        <!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します  -->
        <!-- <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
            <input name='chat_group[user_ids][]' type='hidden' value='22'>
            <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
        </div> -->
      </div>
    </div>
    <div class='chat-group-form__field clearfix'>
      <div class='chat-group-form__field--left'></div>
      <div class='chat-group-form__field--right'>
        <input type="submit" name="commit" value="Save" class="chat-group-form__action-btn" data-disable-with="Save" />
      </div>
    </div>
  </form>
</div>

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key,value|
    = content_tag :div, value, class:  key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / fontsome
    %link{crossorigin: "anonymous", href: "https://use.fontawesome.com/releases/v5.7.2/css/all.css", integrity: "sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr", rel: "stylesheet"}/
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.contents__main-contents__body__text{"data-message-id": message.id  }
  .contents__main-contents__body__text__user= message.user.name
  .contents__main-contents__body__text__time= message.created_at
  .contents__main-contents__body__text__message
    - if message.content.present?
      .contents__main-contents__body__text__message
        = message.content
    = image_tag message.image.url, class: 'contents__main-contents__body__text__image' if message.image.present?

app/views/messages/index.html.haml
=javascript_tag do
  window.leastMessage = #{raw @messages.last.to_json}

.contents
  = render 'shared/side_contents'
  / メインヘッダ部
  .contents__main-contents
    .contents__main-contents__main-header
      .contents__main-contents__main-header__link
        = link_to edit_group_path(@group) do
          .contents__main-contents__main-header__link__box Edit
      .contents__main-contents__main-header__space
      .contents__main-contents__main-header__group
        = @group.name
      .contents__main-contents__main-header__space2
      .contents__main-contents__main-header__member
        member:
        - @group.users.each do |user|
          = user.name
      .contents__main-contents__main-header__border

    .contents__main-contents__body
      - if @messages.last != nil
        = hidden_field :leastMessageId , class: "leastMessageId", value: "#{@messages.last.id}"
        .contents__main-contents__body__space3
        = render @messages

    / 検索フォーム

    .contents__main-contents__footter
      = form_for [@group, @message], class: "contents__main-contents__footter__form" do |f|
        = f.text_field :content ,class: 'contents__main-contents__footter__form__input', placeholder: ' type a messagess'
        .contents__main-contents__footter__form__image
          = f.label :image, class: '.contents__main-contents__footter__form__image' do
            = fa_icon 'image'
            = f.file_field :image, class: 'hidden contents__main-contents__footter__form__image__none'
        = f.submit 'Send', class: 'contents__main-contents__footter__form__button'

app/views/shared/_side_contents.html.haml
.contents__left-contents
  .contents__left-contents__userform
    .contents__left-contents__userform__user
      = current_user.name
    .contents__left-contents__userform__font
      = link_to new_group_path  do
        = fa_icon 'edit'
      = link_to edit_user_path(current_user)  do
        = fa_icon 'cog'
.contents__left-contents__groupform
  - current_user.groups.each do |group|
    = link_to group_messages_path(group) do
      .contents__left-contents__groupform__group
        = group.name
      .contents__left-contents__groupform__group__text
        = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/update.html.haml
テスト